jobs:
  fullbuild:
    name: Build and Verify
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: JDK Setup
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: D-BUS AT-SPI Installation
      run: sudo apt-get -y install at-spi2-core
    - continue-on-error: true
      name: Build
      run: ./gradlew build -x test -PskipSpotless
    - continue-on-error: true
      name: Test
      uses: coactions/setup-xvfb@v1.0.1
      with:
        run: ./gradlew jacocoTestReport -PskipSpotless
    - continue-on-error: true
      name: Publish Test Results
      uses: dorny/test-reporter@v1
      with:
        name: JUnit test results
        path: '**/test-results/**/*.xml'
        reporter: java-junit
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{!github.event.pull_request.head.repo.fork}}
      name: Static Analysis
      run: ./gradlew sonar -PskipSpotless
    - continue-on-error: true
      name: Code Style Validation
      run: ./gradlew spotlessCheck
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
