jobs:
  greeting:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/first-interaction@v1
      with:
        issue-message: Thank you for your reporting your first LITIENGINE issue! We
          are looking forward to your further contributions.
        pr-message: Amazing, your first Pull Request in the LITIENGINE repository!
          You have earned the rank of "contributor" - let us know your nickname in
          the Forum and on Discord so we can reward you with the new role :).
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Greetings
on:
  repository_dispatch:
    types: trigger-ga___greetings.yml
