jobs:
  codeberg:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        ssh_private_key: ${{ secrets.CODEBERG_SSH }}
        target_repo_url: git@codeberg.org:gurkenlabs/LITIENGINE.git
name: Mirror To Codeberg
on:
  repository_dispatch:
    types: trigger-ga___mirror.yml
